# Generated by Django 4.1.2 on 2022-10-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneakercard',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='Колличество'),
            preserve_default=False,
        ),
    ]
